logging:
  config: classpath:logback-${spring.profiles.active}.xml

spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
      allow-pool-suspension: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      use-new-id-generator-mappings: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true

---
spring:
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8888
      name: cloud-config

---
spring:
  profiles:
    active: product
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/studydb?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: study
      password: study